server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
  mvc:
    static-path-pattern: /wx/storage/fetch/**
  aop:
    auto: true
# spring.servlet.multipart.enable 和 spring.aop.auto 的默认值为 true，故可不引入

pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
mybatis:
  type-handlers-package: com.cskaoyan.mall.handler
